### ISSUE TITLE
Need an Intel/ARM universal build

### ISSUE THREAD

**Issue by avv3lenato** [alex-free/dreamcast-cdi-burner#1]
Need an Intel/ARM universal build, otherwise is unusable on the latest versions of macOS

**Comment by alex-free** [comment]
> Need an Intel/ARM universal build, otherwise is unusable on the latest versions of macOS

Yea your right, don’t have an Intel or ARM Mac, this won’t work on ARM Macs anyways as is because it expects an internal CD/DVD burner. 

If you have an Intel Mac, can you install Xcode, download the source, and run the ‘build-all’ command? That should install it from source for you, then you can launch the ‘/Applications/DCDIB.app’ and see if it works. Please report back if you do so!

**Comment by avv3lenato** [comment]
An Intel Mac do not have an internal CD/DVD burner in years... So first it's important to support external drives to test the app. Anyway, a big thx! I really miss an app that burn Dreamcast image easely.

**Comment by alex-free** [comment]
> An Intel Mac do not have an internal CD/DVD burner in years... So first it's important to support external drives to test the app. Anyway, a big thx! I really miss an app that burn Dreamcast image easely.

An Intel version for Mac OS X 10.6-10.14 is now available as of version 1.0.7, so I'm closing this issue :)
https://github.com/alex-free/dreamcast-cdi-burner/releases/download/1.0.7/dreamcast_cdi_burner_1.0.7_mac_i386.zip

**Comment by adamfratino** [comment]
@alex-free any plans to add support for 10.15?

**Comment by alex-free** [comment]
> @alex-free any plans to add support for 10.15?

I will make a 64 bit version available that will work on 10.15+ in the next release.

**Comment by adamfratino** [comment]
Amazing, thank you so much!

**Comment by cptndrip** [comment]
> > @alex-free any plans to add support for 10.15?
> 
> I will make a 64 bit version available that will work on 10.15+ in the next release.

Hi! Thanks for your work. And I am part of the potential users for a 64bits version! :)

**Comment by nelsonvassalo** [comment]
Adding my take here to say I also desperately need this as my go-to solution 🥲 No luck with Discjuggler under Parallels, and running macOS 12 with external drive. Thanks so much for tour work, happy to help in any way I can.

**Comment by alex-free** [comment]
> Adding my take here to say I also desperately need this as my go-to solution 🥲 No luck with Discjuggler under Parallels, and running macOS 12 with external drive. Thanks so much for tour work, happy to help in any way I can.

I'm not sure when I will have time, but all you need to do to make it work on your macOS 12 should be:

-Install Xcode Command Line Tools on your Mac
-Open Terminal:
git clone https://github.com/alex-free/dreamcast-cdi-burner
cd dreamcast-cdi-burner
sudo ./build-all
-Double click /Applications/DCDIB.app to open it.
-Cross fingers...

**Comment by nelsonvassalo** [comment]
Yeah I tried. But no luck. It gives me `bad CPU type in executable: /Applications/DCDIB.app/Contents/MacOS/applet`
 when running DCDIB.app

**Comment by alex-free** [comment]
> Yeah I tried. But no luck. It gives me `bad CPU type in executable: /Applications/DCDIB.app/Contents/MacOS/applet` when running DCDIB.app

I know this isn't a great solution, but if you open Terminal.app and run this it should work:
/Applications/DCDIB.app/bin/cdib yourgame.cdi

Replace yourgame.cdi with the full file path to your .cdi.

**Comment by nelsonvassalo** [comment]
Closer, closer I need to pass it options — `At least one argument is required!` — What would this be? 

I also fixed a couple of type errors `build-all` was throwing on macOS and that took the process a lot farther than before before erroring out near the end of compilation. Are PR's open?

**Comment by alex-free** [comment]
> Closer, closer I need to pass it options — `At least one argument is required!` — What would this be?
> 
> I also fixed a couple of type errors `build-all` was throwing on macOS and that took the process a lot farther than before before erroring out near the end of compilation. Are PR's open?

Yes PR's are open.

You are referring to the /Applications/DCDIB.app/bin/cdib  saying one argument is required right? The one argument is the cdi file.

If the build-all script didn't compile all the way however the above won't work. What does your Terminal.app output look like with the build-all script running?

**Comment by nelsonvassalo** [comment]
Closer, closer. Now bumping into 
```
Found image file. Opening...
This is a v3.5 image

Destination path: '/Users/ME/.dcdib_tmp'

/Users/ME/.dcdib_tmp: Bad address
Could not find destination pathBurning...
Failed To Find Burn Files, Nothing Burned!
```

**Comment by nelsonvassalo** [comment]
Also `/Users/ME/.dcdib_tmp: Bad address`

**Comment by alex-free** [comment]
> Closer, closer. Now bumping into
> 
> ```
> Found image file. Opening...
> This is a v3.5 image
> 
> Destination path: '/Users/ME/.dcdib_tmp'
> 
> /Users/ME/.dcdib_tmp: Bad address
> Could not find destination pathBurning...
> Failed To Find Burn Files, Nothing Burned!
> ```

Open the /Applications/DCDIB.app/bin/cdib file in text edit and change the 3rd line from

tmp=~/.dcdib_tmp 

to:

tmp=~/Desktop/.dcdib_tmp

And let me know what happens

**Comment by nelsonvassalo** [comment]
No luck, still throwing `bad address`. I tried even changing it to a regular (non-hidden folder), it seems to always hit here:
```
# unmount_cd

rm -rf $tmp
mkdir $tmp
echo "Extracting $cdi..."
$cdirip "$1" $tmp 
cd $tmp 
```

I suspected `unmount` could be culprit so tried commenting but also not luck. My guess was because these lines seem to try to find a default optical drive on the machine and I'm using external?

```
unmount_cd () {
if [ "$os" = "Darwin" ]; then
	launchctl unload /System/Library/LaunchDaemons/com.apple.diskarbitrationd.plist > /dev/null 2>&1
	disktool -u disk1 0 > /dev/null 2>&1
else
    umount /mnt/cdrom > /dev/null 2>&1
fi
}
```

**Comment by alex-free** [comment]
> No luck, still throwing `bad address`. I tried even changing it to a regular (non-hidden folder), it seems to always hit here:
> 
> ```
> # unmount_cd
> 
> rm -rf $tmp
> mkdir $tmp
> echo "Extracting $cdi..."
> $cdirip "$1" $tmp 
> cd $tmp 
> ```
> 
> I suspected `unmount` could be culprit so tried commenting but also not luck. My guess was because these lines seem to try to find a default optical drive on the machine and I'm using external?
> 
> ```
> unmount_cd () {
> if [ "$os" = "Darwin" ]; then
> 	launchctl unload /System/Library/LaunchDaemons/com.apple.diskarbitrationd.plist > /dev/null 2>&1
> 	disktool -u disk1 0 > /dev/null 2>&1
> else
>     umount /mnt/cdrom > /dev/null 2>&1
> fi
> }
> ```

Nope. External drives work just fine. 

This is something to do with macOS 12 and all the changes Apple keeps making every update breaking existing open source software and whatnot. I gotta be honest I will never be using Mac OS 12 or anything newer then probably 10.11 which is already supported so I highly doubt this will ever get support.

I know it's not the answer you want to hear, but I just have no modern macs and no desire to buy any or use a modern Mac OS.

**Comment by nelsonvassalo** [comment]
Cool, Anyway sending a PR so at least it builds on macOS 12, and maybe someone can take it from there… :(

**Comment by nelsonvassalo** [comment]
@adamfratino @avv3lenato wanna give it a shot together?
