### ISSUE TITLE
 Error while loading shared libraries: bincdirip2: cannot open shared object file

### ISSUE THREAD

**Issue by neoraph** [alex-free/dreamcast-cdi-burner#10]
Hello, 
I am running on Debian12 and I found out your awesome software, so I wanted to give a try. I did the process to install it from sources with the build script, I did not look too much in details, but I got this error when I am trying to burn an image :

` sudo ./dcdib /home/raphael/Downloads/\[CDI\]\ The\ King\ of\ Fighters\ -\ Evolution\ \(US\)\(VGA\ Compatible\).7z 
Dreamcast CDI Burner v1.0.8
By Alex Free

Info: Using default CD burner device: /dev/sr0

Extracting /home/raphael/Downloads/[CDI] The King of Fighters - Evolution (US)(VGA Compatible).7z...\n
bincdirip2: error while loading shared libraries: bincdirip2: cannot open shared object file
Uncaught error in ./dcdib:66
raphael@debian:~/dreamcast/dreamcast-cdi-burner/dcdib-1.0.8-unknown$`

Do I need to so something about this shared library ?

Thank you!

**Comment by alex-free** [comment]
> Hello, I am running on Debian12 and I found out your awesome software, so I wanted to give a try. I did the process to install it from sources with the build script, I did not look too much in details, but I got this error when I am trying to burn an image :
> 
> ` sudo ./dcdib /home/raphael/Downloads/[CDI]\ The\ King\ of\ Fighters\ -\ Evolution\ (US)(VGA\ Compatible).7z Dreamcast CDI Burner v1.0.8 By Alex Free
> 
> Info: Using default CD burner device: /dev/sr0
> 
> Extracting /home/raphael/Downloads/[CDI] The King of Fighters - Evolution (US)(VGA Compatible).7z...\n bincdirip2: error while loading shared libraries: bincdirip2: cannot open shared object file Uncaught error in ./dcdib:66 raphael@debian:~/dreamcast/dreamcast-cdi-burner/dcdib-1.0.8-unknown$`
> 
> Do I need to so something about this shared library ?
> 
> Thank you!

Working on an update now to fix building from source, did the pre-compiled release not work for you?

**Comment by neoraph** [comment]
Hi! 
> Working on an update now to fix building from source, did the pre-compiled release not work for you?

I did not do the test, so just did it now. Yes, it is seems working fine when I execute the pre-compiled release, but I still cannot compile the release from source.

**Comment by alex-free** [comment]
> Hi!
> 
> > Working on an update now to fix building from source, did the pre-compiled release not work for you?
> 
> I did not do the test, so just did it now. Yes, it is seems working fine when I execute the pre-compiled release, but I still cannot compile the release from source.

I just pushed an update to the build script. Let me know if this fixes your issue.

**Comment by neoraph** [comment]
sorry, it seems I got the same issue...
but please, take it easy as the pre-compiled release is working well !

**Comment by alex-free** [comment]
> sorry, it seems I got the same issue...
> 
> but please, take it easy as the pre-compiled release is working well ! 

I'm really proud of the portable Linux release compatibility 😀 

The dcdib-1.0.8-unknown seems strange to me when you try to compile from source, it seems like the build script is failing to compile one of the software packages. Could you run the build script and copy all output to a text file, then upload that here?

**Comment by neoraph** [comment]
Hi!

> The dcdib-1.0.8-unknown seems strange to me when you try to compile from source, it seems like the build script is failing to compile one of the software packages

yeah, I was thinking the same, I checked it a bit out, and the unknown come from the build script for this command : `arch=$(uname -p)`
I checked it out, and effectively, running the command `uname -p` returns 'unknown'. I am not sure why, however, by running the command `uname -m` will give me 'x86_64' which I think is what we are expected. I did not fully check the code but I think it is only use for the folder name so maybe it is not a big deal (but nice to fix if it works for other machines than mine)
Even with the change, I do have the same error at the end, when I tried to execute the application.

Please find in attachment the compile.log.
[compile.log](https://github.com/alex-free/dreamcast-cdi-burner/files/14774615/compile.log)

It is the log executed with the non-modified build script (so the folder name will contain the 'unknown' word). However, you will be able to see that I got some warning and some include seems missing, but the script continues until the end.

Looking forward from your analysis !

**Comment by alex-free** [comment]
> Hi!
> 
> > The dcdib-1.0.8-unknown seems strange to me when you try to compile from source, it seems like the build script is failing to compile one of the software packages
> 
> yeah, I was thinking the same, I checked it a bit out, and the unknown come from the build script for this command : `arch=$(uname -p)` I checked it out, and effectively, running the command `uname -p` returns 'unknown'. I am not sure why, however, by running the command `uname -m` will give me 'x86_64' which I think is what we are expected. I did not fully check the code but I think it is only use for the folder name so maybe it is not a big deal (but nice to fix if it works for other machines than mine) Even with the change, I do have the same error at the end, when I tried to execute the application.
> 
> Please find in attachment the compile.log. [compile.log](https://github.com/alex-free/dreamcast-cdi-burner/files/14774615/compile.log)
> 
> It is the log executed with the non-modified build script (so the folder name will contain the 'unknown' word). However, you will be able to see that I got some warning and some include seems missing, but the script continues until the end.
> 
> Looking forward from your analysis !

Nice find! On Fedora and Pop!OS both return the same thing so I will change that command.
![Screenshot from 2024-03-27 17-08-49](https://github.com/alex-free/dreamcast-cdi-burner/assets/72545918/c91c5d1b-99ae-4214-937c-60f71b5887da)

CDRTools compilation is actually expected to error like that before automatically rebuilding successfully (don't ask me why, but it is a known [thing](https://www.linuxquestions.org/questions/slackware-14/building-cdrtools-on-current-4175703887/#post6303351), the build system is quite strange but it looks like everything is compiling fine. 

Might grab a Debian 12 VM and see what is going on if I can't debug this further on my Pop!OS system.

**Comment by alex-free** [comment]
Good news, everything is now working as expected!

I want to do a few more things before I push v1.0.9, but you don't need to wait as the fix is in the git repo.

Should be able to:
`rm -rf dreamcast-cdi-burner`
`git clone --recursive https://github.com/alex-free/dreamcast-cdi-burner`
`cd dreamcast-cdi-burner`
`./build`
`cd dcdib-v1.0.8-x86_64`
`sudo ./dcdib yourcdifile.cdi`

Would you also appreciate .7z support? Like no need to extract it beforehand, can just do ./dcdib yourcdifile.7z and dcdib could then handle the extraction and select the .cdi file automatically? Just thought of adding that too.

**Comment by neoraph** [comment]
Hi, 
It works great now, thank you for the update !
for the 7z, it is up to you, having the support would be nice ofc but it is not so mandatory.

**Comment by alex-free** [comment]
> Hi, It works great now, thank you for the update ! for the 7z, it is up to you, having the support would be nice ofc but it is not so mandatory.



> Hi, It works great now, thank you for the update ! for the 7z, it is up to you, having the support would be nice ofc but it is not so mandatory.

Just pushed v1.0.9 with this support, enjoy
