### ISSUE TITLE
How to select a slower burn speed?

### ISSUE THREAD

**Issue by moonbit5** [alex-free/dreamcast-cdi-burner#3]
How can I adjust the burn speed? I've tried changing `-speed=8` to `-speed=2` however it's still trying to burn at 10x!

Could it be my dvd burner?

**Comment by james-stocks** [comment]
Did you fix this? I set speed to `4` and it seems to acknowledge that when the program launches but proceeds to burn at speed 16...

```
Burner: /dev/sr0

Burn speed: 4x
Extracted CDI file: /media/james/work/battletoads.cdi...
/media/james/work/battletoads.cdi uses the data+data self-boot method. This disc will self-boot on all rev 0 and rev 1 Sega Dreamcast consoles.
Cdrecord-ProDVD-ProBD-Clone 3.02a09 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2016 Joerg Schilling
TOC Type: 3 = CD-ROM XA mode 2
scsidev: '/dev/sr0'
devname: '/dev/sr0'
scsibus: -2 target: -2 lun: -2
Warning: Open by 'devname' is unintentional and not supported.
Linux sg driver version: 3.5.27
Using libscg version 'schily-0.9'.
SCSI buffer size: 64512
atapi: 1
Device type    : Removable CD-ROM
Version        : 5
Response Format: 2
Capabilities   : 
Vendor_info    : 'ATAPI   '
Identifikation : 'iHAS124   E     '
Revision       : '4L08'
Device seems to be: Generic mmc2 DVD-R/DVD-RW/DVD-RAM.
Current: CD-R
Profile: DVD+R/DL 
Profile: DVD+R 
Profile: DVD+RW 
Profile: DVD-R/DL layer jump recording 
Profile: DVD-R/DL sequential recording 
Profile: DVD-RW sequential recording 
Profile: DVD-RW restricted overwrite 
Profile: DVD-RAM 
Profile: DVD-R sequential recording 
Profile: DVD-ROM 
Profile: CD-RW 
Profile: CD-R (current)
Profile: CD-ROM 
Profile: Removable Disk 
Using generic SCSI-3/mmc   CD-R/CD-RW driver (mmc_cdr).
Driver flags   : MMC-3 SWABAUDIO BURNFREE FORCESPEED 
Supported modes: TAO PACKET SAO SAO/R96P SAO/R96R RAW/R16 RAW/R96P RAW/R96R
Drive buf size : 524288 = 512 KB
cdrecord2: Warning: Cannot read drive buffer.
cdrecord2: Warning: The DMA speed test has been skipped.
FIFO size      : 4194304 = 4096 KB
Track 01: data   642 MB        
Total size:      737 MB (73:03.49) = 328762 sectors
Lout start:      737 MB (73:05/37) = 328762 sectors
Current Secsize: 2048
ATIP info from disk:
  Indicated writing power: 5
Disk Is not unrestricted
Disk Is not erasable
  Disk sub type: Medium Type A, high Beta category (A+) (3)
  ATIP start of lead in:  -11634 (97:26/66)
  ATIP start of lead out: 359846 (79:59/71)
Disk type:    Short strategy type (Phthalocyanine or similar)
Manuf. index: 3
Manufacturer: CMC Magnetics Corporation

    Capacity  Blklen/Sparesz.  Format-type  Type
    16763814             2048         0x00  No Media Present or Unknown Capacity
Blocks total: 359846 Blocks current: 359846 Blocks remaining: 31084
Forcespeed is OFF.
Starting to write CD/DVD/BD at speed 16 in real TAO mode for multi session.
Last chance to quit, starting real write    0 seconds. Operation starts.
Waiting for reader process to fill input buffer ... input buffer ready.
BURN-Free is OFF.
Performing OPC...
Starting new track at sector: 0
Track 01:  642 of  642 MB written (fifo 100%) [buf 100%]  16.2x.
Track 01: Total bytes read/written: 673300480/673300480 (328760 sectors).
Writing  time:  286.474s (00:04:46.474)
Average write speed  15.8x.
Min drive buffer fill was 100%
Fixating...
Fixating time:   23.238s (00:00:23.238)
cdrecord2: fifo had 10606 puts and 10606 gets.
cdrecord2: fifo was 0 times empty and 10534 times full, min fill was 90%.
Cdrecord-ProDVD-ProBD-Clone 3.02a09 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2016 Joerg Schilling
TOC Type: 3 = CD-ROM XA mode 2
scsidev: '/dev/sr0'
devname: '/dev/sr0'
scsibus: -2 target: -2 lun: -2
Warning: Open by 'devname' is unintentional and not supported.
Linux sg driver version: 3.5.27
Using libscg version 'schily-0.9'.
SCSI buffer size: 64512
atapi: 1
Device type    : Removable CD-ROM
Version        : 5
Response Format: 2
Capabilities   : 
Vendor_info    : 'ATAPI   '
Identifikation : 'iHAS124   E     '
Revision       : '4L08'
Device seems to be: Generic mmc2 DVD-R/DVD-RW/DVD-RAM.
Current: CD-R
Profile: DVD+R/DL 
Profile: DVD+R 
Profile: DVD+RW 
Profile: DVD-R/DL layer jump recording 
Profile: DVD-R/DL sequential recording 
Profile: DVD-RW sequential recording 
Profile: DVD-RW restricted overwrite 
Profile: DVD-RAM 
Profile: DVD-R sequential recording 
Profile: DVD-ROM 
Profile: CD-RW 
Profile: CD-R (current)
Profile: CD-ROM 
Profile: Removable Disk 
Using generic SCSI-3/mmc   CD-R/CD-RW driver (mmc_cdr).
Driver flags   : MMC-3 SWABAUDIO BURNFREE FORCESPEED 
Supported modes: TAO PACKET SAO SAO/R96P SAO/R96R RAW/R16 RAW/R96P RAW/R96R
Drive buf size : 524288 = 512 KB
cdrecord2: Warning: Cannot read drive buffer.
cdrecord2: Warning: The DMA speed test has been skipped.
FIFO size      : 4194304 = 4096 KB
Track 01: data     0 MB        
Total size:        0 MB (00:04.05) = 304 sectors
Lout start:        1 MB (00:06/04) = 304 sectors
Current Secsize: 2048
ATIP info from disk:
  Indicated writing power: 5
Disk Is not unrestricted
Disk Is not erasable
  Disk sub type: Medium Type A, high Beta category (A+) (3)
  ATIP start of lead in:  -11634 (97:26/66)
  ATIP start of lead out: 359846 (79:59/71)
Disk type:    Short strategy type (Phthalocyanine or similar)
Manuf. index: 3
Manufacturer: CMC Magnetics Corporation

    Capacity  Blklen/Sparesz.  Format-type  Type
      328762             2048         0x00  Formatted Media
Blocks total: 359846 Blocks current: 19684 Blocks remaining: 19380
Forcespeed is OFF.
Starting to write CD/DVD/BD at speed 16 in real TAO mode for single session.
Last chance to quit, starting real write    0 seconds. Operation starts.
```

**Comment by alex-free** [comment]
> Did you fix this? I set speed to `4` and it seems to acknowledge that when the program launches but proceeds to burn at speed 16...
> 
> ```
> Burner: /dev/sr0
> 
> Burn speed: 4x
> Extracted CDI file: /media/james/work/battletoads.cdi...
> /media/james/work/battletoads.cdi uses the data+data self-boot method. This disc will self-boot on all rev 0 and rev 1 Sega Dreamcast consoles.
> Cdrecord-ProDVD-ProBD-Clone 3.02a09 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2016 Joerg Schilling
> TOC Type: 3 = CD-ROM XA mode 2
> scsidev: '/dev/sr0'
> devname: '/dev/sr0'
> scsibus: -2 target: -2 lun: -2
> Warning: Open by 'devname' is unintentional and not supported.
> Linux sg driver version: 3.5.27
> Using libscg version 'schily-0.9'.
> SCSI buffer size: 64512
> atapi: 1
> Device type    : Removable CD-ROM
> Version        : 5
> Response Format: 2
> Capabilities   : 
> Vendor_info    : 'ATAPI   '
> Identifikation : 'iHAS124   E     '
> Revision       : '4L08'
> Device seems to be: Generic mmc2 DVD-R/DVD-RW/DVD-RAM.
> Current: CD-R
> Profile: DVD+R/DL 
> Profile: DVD+R 
> Profile: DVD+RW 
> Profile: DVD-R/DL layer jump recording 
> Profile: DVD-R/DL sequential recording 
> Profile: DVD-RW sequential recording 
> Profile: DVD-RW restricted overwrite 
> Profile: DVD-RAM 
> Profile: DVD-R sequential recording 
> Profile: DVD-ROM 
> Profile: CD-RW 
> Profile: CD-R (current)
> Profile: CD-ROM 
> Profile: Removable Disk 
> Using generic SCSI-3/mmc   CD-R/CD-RW driver (mmc_cdr).
> Driver flags   : MMC-3 SWABAUDIO BURNFREE FORCESPEED 
> Supported modes: TAO PACKET SAO SAO/R96P SAO/R96R RAW/R16 RAW/R96P RAW/R96R
> Drive buf size : 524288 = 512 KB
> cdrecord2: Warning: Cannot read drive buffer.
> cdrecord2: Warning: The DMA speed test has been skipped.
> FIFO size      : 4194304 = 4096 KB
> Track 01: data   642 MB        
> Total size:      737 MB (73:03.49) = 328762 sectors
> Lout start:      737 MB (73:05/37) = 328762 sectors
> Current Secsize: 2048
> ATIP info from disk:
>   Indicated writing power: 5
> Disk Is not unrestricted
> Disk Is not erasable
>   Disk sub type: Medium Type A, high Beta category (A+) (3)
>   ATIP start of lead in:  -11634 (97:26/66)
>   ATIP start of lead out: 359846 (79:59/71)
> Disk type:    Short strategy type (Phthalocyanine or similar)
> Manuf. index: 3
> Manufacturer: CMC Magnetics Corporation
> 
>     Capacity  Blklen/Sparesz.  Format-type  Type
>     16763814             2048         0x00  No Media Present or Unknown Capacity
> Blocks total: 359846 Blocks current: 359846 Blocks remaining: 31084
> Forcespeed is OFF.
> Starting to write CD/DVD/BD at speed 16 in real TAO mode for multi session.
> Last chance to quit, starting real write    0 seconds. Operation starts.
> Waiting for reader process to fill input buffer ... input buffer ready.
> BURN-Free is OFF.
> Performing OPC...
> Starting new track at sector: 0
> Track 01:  642 of  642 MB written (fifo 100%) [buf 100%]  16.2x.
> Track 01: Total bytes read/written: 673300480/673300480 (328760 sectors).
> Writing  time:  286.474s (00:04:46.474)
> Average write speed  15.8x.
> Min drive buffer fill was 100%
> Fixating...
> Fixating time:   23.238s (00:00:23.238)
> cdrecord2: fifo had 10606 puts and 10606 gets.
> cdrecord2: fifo was 0 times empty and 10534 times full, min fill was 90%.
> Cdrecord-ProDVD-ProBD-Clone 3.02a09 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2016 Joerg Schilling
> TOC Type: 3 = CD-ROM XA mode 2
> scsidev: '/dev/sr0'
> devname: '/dev/sr0'
> scsibus: -2 target: -2 lun: -2
> Warning: Open by 'devname' is unintentional and not supported.
> Linux sg driver version: 3.5.27
> Using libscg version 'schily-0.9'.
> SCSI buffer size: 64512
> atapi: 1
> Device type    : Removable CD-ROM
> Version        : 5
> Response Format: 2
> Capabilities   : 
> Vendor_info    : 'ATAPI   '
> Identifikation : 'iHAS124   E     '
> Revision       : '4L08'
> Device seems to be: Generic mmc2 DVD-R/DVD-RW/DVD-RAM.
> Current: CD-R
> Profile: DVD+R/DL 
> Profile: DVD+R 
> Profile: DVD+RW 
> Profile: DVD-R/DL layer jump recording 
> Profile: DVD-R/DL sequential recording 
> Profile: DVD-RW sequential recording 
> Profile: DVD-RW restricted overwrite 
> Profile: DVD-RAM 
> Profile: DVD-R sequential recording 
> Profile: DVD-ROM 
> Profile: CD-RW 
> Profile: CD-R (current)
> Profile: CD-ROM 
> Profile: Removable Disk 
> Using generic SCSI-3/mmc   CD-R/CD-RW driver (mmc_cdr).
> Driver flags   : MMC-3 SWABAUDIO BURNFREE FORCESPEED 
> Supported modes: TAO PACKET SAO SAO/R96P SAO/R96R RAW/R16 RAW/R96P RAW/R96R
> Drive buf size : 524288 = 512 KB
> cdrecord2: Warning: Cannot read drive buffer.
> cdrecord2: Warning: The DMA speed test has been skipped.
> FIFO size      : 4194304 = 4096 KB
> Track 01: data     0 MB        
> Total size:        0 MB (00:04.05) = 304 sectors
> Lout start:        1 MB (00:06/04) = 304 sectors
> Current Secsize: 2048
> ATIP info from disk:
>   Indicated writing power: 5
> Disk Is not unrestricted
> Disk Is not erasable
>   Disk sub type: Medium Type A, high Beta category (A+) (3)
>   ATIP start of lead in:  -11634 (97:26/66)
>   ATIP start of lead out: 359846 (79:59/71)
> Disk type:    Short strategy type (Phthalocyanine or similar)
> Manuf. index: 3
> Manufacturer: CMC Magnetics Corporation
> 
>     Capacity  Blklen/Sparesz.  Format-type  Type
>       328762             2048         0x00  Formatted Media
> Blocks total: 359846 Blocks current: 19684 Blocks remaining: 19380
> Forcespeed is OFF.
> Starting to write CD/DVD/BD at speed 16 in real TAO mode for single session.
> Last chance to quit, starting real write    0 seconds. Operation starts.
> ```
> 
> 

The program is working correctly. Your cd burner is incapable of burning at your requested speed of 4x, the lowest it can do is 16x so it goes to that (pretty common for newer burners, they give you less flexibility with higher minimum burn speeds).
