### ISSUE TITLE
are you sure discs are self bootables?

### ISSUE THREAD

**Issue by legacychimera247** [alex-free/dreamcast-cdi-burner#8]
hello there, just burned two discs with fedora linux and none of them worked, my dc does not even spin them, always asking me to insert the disc

yes my dreamcast can read burned games just fine, any ideas on wht it might be?

**Comment by alex-free** [comment]
The DC does not spin the disc? Sounds like a GDROM drive problem. Even if it wasn't self boot the disc would still spin and at least bring up the CD player in the Dreamcast boot menu. DCDIB does self boot everything I've thrown at it. Try wiping off the laser lens with a microfiber cloth, and troubleshooting with the guided questions below:

1) If you burn with i.e. IMGburn on Windows using the same CD-R media, does anything change?
2) Do you have other burned games burned to the same exact CD-R media that does spin?
3) If you burn with a different CD drive (if possible), does anything change?
4) Are you using high quality CD-Rs (and not a CD-RW)? What is the brand/capacity?
5) What revision is your dreamcast?
6) Is the CD-R you burn readable by your computer?
7) What games have you tried?
8) Can you copy the terminal output and reply with it here?

**Comment by legacychimera247** [comment]
1 i will try that tomorrow
2 no, first time using hp media
3 no, it's the only drive i have for that pc
4 hp media, classic 700 mb 80 minutes
5 second revision and reads backups just fine
6/7 yes for both, tried looney tunes space race taken from coolrom, and king of fighters neowave cdi taken from dc-talk
8 we'll see, guess i need to buy some new media :)

**Comment by alex-free** [comment]
> 1 i will try that tomorrow 2 no, first time using hp media 3 no, it's the only drive i have for that pc 4 hp media, classic 700 mb 80 minutes 5 second revision and reads backups just fine 6/7 yes for both, tried looney tunes space race taken from coolrom, and king of fighters neowave cdi taken from dc-talk 8 we'll see, guess i need to buy some new media :)

Thanks for going through those steps. I look forward to your response/answers.

I will personally try burning those images myself with DCDIB.  I have a revision 1 dreamcast. I have heard that some revision 2 dreamcasts have issues with some CDI file types. Some CDI files are WAV+DATA format, and others are DATA+DATA format. The REV 1 like I have supports all types of CDI files. The Rev 2 I've heard only supports DATA+DATA. I've heard the Rev 0 only supports WAV+DATA. I need the terminal output of your burn to confirm, but this is most likely the whole issue.
If you could send me the month/year on the bottom of the Dreamcast that would help a bit.

If that does turn out to be the issue, I could possibly have a new DCDIB update force convert to DATA+DATA for Rev 2s like you have. If you have anymore questions let me know. 

I do highly recommend better CD-R media. You want Verbatim DataLifePlus, not regular Verbatim from some retail store. Your CD drive is most likely fine but I have found some CD drives don't burn lower quality CD-R media good enough for the console to read it. If you have any more questions on this let me know.

**Comment by alex-free** [comment]
Alright, looks like I was right! I do believe you have a Revision 2 Dreamcast console which **can only boot DATA+DATA CDI file types**.  I looked at both games you sent and the first track in both is a WAV/audio file:

![kof neo wave](https://user-images.githubusercontent.com/72545918/199137308-7af6d96a-62d1-4caf-a7b5-5a31b7f81d46.png)
![looney](https://user-images.githubusercontent.com/72545918/199137310-4d67c687-ba45-469d-a371-f860ebd2600f.png)

So what does this mean?
- DCDIB is technically not doing anything wrong, the CDI files are incompatible at a hardware level.
- You need to convert the CDI file from AUDIO+DATA to DATA+DATA. The first track needs to be a DATA iso file, not an audio .wav file since your console is not supporting that type.
- Please confirm that you can boot DATA+DATA style CDI files. If you look at the terminal output the first track ripped should not say audio/2352. I fully expect every CD-R you've burned which currently works on your Revision 2 Dreamcast just happened to be DATA+DATA until now when you tested DCDIB out.  IMGBurn or any other software would still make CD-R coasters for your specific console revision I'd expect, if the CDI file type was also DATA+DATA.
- I will attempt to add automatic conversion to DATA+DATA so that this will work seemlessly on your console.
- Your CD-R media is probably fine.

**Comment by legacychimera247** [comment]
unfortunately there is only one shop in my town still selling recordable media, so i have to get what they have

other than that i can tell you i already had a perfectly working backup of looney tunes space race, but lost it somewhere

in the next days anyway i will try to make another burn to let you have an output and burn the same disc in imgburn just to see...

**Comment by alex-free** [comment]
> unfortunately there is only one shop in my town still selling recordable media, so i have to get what they have
> 
> other than that i can tell you i already had a perfectly working backup of looney tunes space race, but lost it somewhere
> 
> in the next days anyway i will try to make another burn to let you have an output and burn the same disc in imgburn just to see...

Is it possible that the looney tunes space race backup CD-R you had that did work on your revision 2 console was a different file from somewhere else other then coolrom? It could of been a DATA+DATA version. The coolrom version is for sure AUDIO+DATA.  If you can burn a disc which works in imgburn then my theory is invalidated, but if the imgburn disc does the same thing then it confirms my theory.

I'll look into converting the looney toons cdi to DATA+DATA format and you could also test that out.

I would hold off on buying different CD-Rs as that may not be the issue.

**Comment by alex-free** [comment]
Alright I found a DATA+DATA game. Google cdromance metropolis street racer. You want Metropolis Street Racer (US)[YZB].cdi .

Please do the following when you have time to help me figure out this issue:
1) Try burning 'Metropolis Street Racer (US)[YZB] .cdi' with the latest/current DCDIB v1.0.8 and let me know if it works.
2) Try burning  the same rip of looney tunes space race with IMGBurn on Windows and let me know if it works.
3) Try burning the same rip of looney tunes space race with the special version of DCDIB attached and let me know if it works.

[dcdib-1.0.8-x86_64-TEST.zip](https://github.com/alex-free/dreamcast-cdi-burner/files/9906455/dcdib-1.0.8-x86_64-TEST.zip)

**Comment by legacychimera247** [comment]
Sorry to say that but my msr is actually an original copy :p  anyway i'll try the other two options and report

just to be clear, my dc is a pal second model, the one with va1 written on it , so basically the most common one

**Comment by legacychimera247** [comment]
tried to burn kof neowave right now with imgburn, and it does not work, same as linux, will now try space race with your new build

**Comment by legacychimera247** [comment]
burned space race with your test build, same exact result, at this point it may be the file itself?trying with another file, will report

unfortunately i'm on my last blank disc, so if it goes wrong we'll need to wait till i buy some new ones

as for the output, just discovered that blackbox does not support copying yet, so here's a screencast...

[Video del 01-11-2022 15:31:36.webm](https://user-images.githubusercontent.com/22254556/199268606-b72ff634-dce8-4ad0-a581-efac3c514416.webm)

**Comment by alex-free** [comment]
> burned space race with your test build, same exact result, at this point it may be the file itself?trying with another file, will report
> 
> unfortunately i'm on my last blank disc, so if it goes wrong we'll need to wait till i buy some new ones
> 
> as for the output, just discovered that blackbox does not support copying yet, so here's a screencast...
> Video.del.01-11-2022.15.31.36.webm

My theory seems correct. There are different types of CDI files, DATA+DATA and AUDIO+DATA formats. **Your Revision 2 Sega Dreamcast can not boot AUDIO+DATA format CDI files. There is nothing wrong with the CDI files themelves**. I need you to burn MSR from that site. It should work on your Dreamcast because unlike all of these other games you've tested it is an **DATA+DATA CDI file which should work on your Rev 2 Dreamcast**. AFAIK:

Rev 0 Dreamcasts only support AUDIO+DATA CDI files.
Rev 1 Dreamcasts supports AUDIO+DATA and DATA+DATA CDI files.
Rev 2 Dreamcasts only support DATA+DATA CDI files.

You have to convert the files from AUDIO+DATA to DATA+DATA. I'm not sure what the best way to do that is, I have a rev 1 dreamcast and only have heard of Rev 2 dreamcasts havinig this potentional issue, but never knew if it was real or not.

I hope that makes sense.
1) IMGburn is fine.
2) DCDIB is fine.
3) Your CD-R media is fine.
4) Your Dreamcast does not support all CDI filetypes. It only will boot DATA+DATA style ones. It will NOT boot AUDIO+DATA CDI files.
5) You can convert AUDIO+DATA CDI files to DATA+DATA CDI files but It's a bit involved. I'm gonna look into it myself to see if it is possible for DCDIB to have a new mode which auto-converts the files to the right type for Rev 2 Dreamcasts on the fly.

Anyway you could take a picture of the Dreamcast's bottom so I can see the label with the circled number 2?

**Comment by legacychimera247** [comment]
when i said it was a second revision i meant second model, my dc as already stated is a va1, and there is a one in the circle under the console

anyway, 2 things

1 ok i will try your metropolis street racers :)
2 the old game surely was the echelon release of space race cause it's the only cdi with my language, i'm actually looking for that...

**Comment by alex-free** [comment]
> when i said it was a second revision i meant second model, my dc as already stated is a va1, and there is a one in the circle under the console
> 
> anyway, 2 things
> 
> 1 ok i will try your metropolis street racers :) 2 the old game surely was the echelon release of space race cause it's the only cdi with my language, i'm actually looking for that...

Interesting. So there is a circled 1 on the bottom and not a 2? That's what I meant. Can I get a picture of the bottom of your console?

If you have a circled 1 on the bottom completely disregard what I've previously said. I'd imagine MSR wouldn't work either but it wouldn't hurt to try. I think the HP media is the actual problem. You can order Verbatim data life plus online for real cheap: https://www.verbatim.com/prod/optical-media/professional-optical/dataLife-plus-cd-r/cd-recordable-datalife-plus-shiny-silver/ . The CD-R brand really can matter. As you can see imgburn isn't doing any better then DCDIB, so I can only guess that the HP CD-Rs you are using are not reflective enough for your Dreamcast to read them.

The ECHELON releases may have been DATA+DATA format from what little I've read, who knows it may still be the problem. Definitely give it a try to rule that issue out.

Maybe it wouldn't also hurt to try burning an audio CD and seeing if the DC can read that?

**Comment by legacychimera247** [comment]
A new audio cd with the hp?cause i already have some burned audio discs

will send you the photo in the morning anyway

as for the echelon release, i am just guessing honestly, i donwloaded the m6 release which was pal, but it was a damn gdi, now i'm trying another file cause the echelon release seems so hard to find, but since i had lot of releases from echelon and from what i read the echelon release is pal, i guess it was that one

oh well, i'm actually considering buying the game...

**Comment by alex-free** [comment]
> A new audio cd with the hp?cause i already have some burned audio discs
> 
> will send you the photo in the morning anyway
> 
> as for the echelon release, i am just guessing honestly, i donwloaded the m6 release which was pal, but it was a damn gdi, now i'm trying another file cause the echelon release seems so hard to find, but since i had lot of releases from echelon and from what i read the echelon release is pal, i guess it was that one
> 
> oh well, i'm actually considering buying the game...

Yea, if you burn an audio CD to a HP CD-R and the CD-R still can't be read by the console it would confirm that the HP media is the issue.

If you burn the specific MSR file I mentioned before and it works then that would confirm that the HP media is fine but the CDI format is not compatible with your console. I can figure out how to make it compatible in such a case I just need to know if that is the problem.

You could indeed just buy the game, but from a technical standpoint I am really curious what issue this actually is for you. 

As for the revision stuff, I really just want to know what month/year and what circled number is on the bottom label of the DC that's all.

**Comment by legacychimera247** [comment]
Sorry for the bad photo, anyway i'll buy some more cds in the next days and let you know

in the meantime, which one do you prefer first?the audio cd or the msr iso?
![20221102_125356](https://user-images.githubusercontent.com/22254556/199483920-17b62404-5af7-4272-b537-c0471756f8ee.jpg)

**Comment by alex-free** [comment]
> Sorry for the bad photo, anyway i'll buy some more cds in the next days and let you know
> 
> in the meantime, which one do you prefer first?the audio cd or the msr iso? ![20221102_125356](https://user-images.githubusercontent.com/22254556/199483920-17b62404-5af7-4272-b537-c0471756f8ee.jpg)

Audio CD. Your console is a rev 1 (circled number 1 on label).

**Comment by legacychimera247** [comment]
I just had the greatest surprise of my life, i made an audio cd and the dreamcast is not even spinning it

at this point i tried with three more audio cds

1th was made by me with flac files taken from bandcamp - media is sony - not even spinning

2nd was made by artist but it's a cdr - can't see brand as there's a cover on the disc - not even spinning

3rd was made by an indie label but it should be laser pressed - perfectly working

now, after this discovery i guess i won't sleep at night anymore

i guess it's now time for msr?

**Comment by alex-free** [comment]
> I just had the greatest surprise of my life, i made an audio cd and the dreamcast is not even spinning it
> 
> at this point i tried with three more audio cds
> 
> 1th was made by me with flac files taken from bandcamp - media is sony - not even spinning
> 
> 2nd was made by artist but it's a cdr - can't see brand as there's a cover on the disc - not even spinning
> 
> 3rd was made by an indie label but it should be laser pressed - perfectly working
> 
> now, after this discovery i guess i won't sleep at night anymore
> 
> i guess it's now time for msr?

Don't bother burning MSR. Your CD-R media is poor quality and not usable with the Dreamcast. You'll need to aquire better CD-R media, preferably Verbatim DataLifePlus as mentioned.

I'm going to close this issue since this is not directly related to DCDIB.
